#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_DOOR_LOCK_GESTURE_ACCESS=y

# CONFIG_VIDEO=y
# CONFIG_SPI=y

# Frame forwarding over serial.
# CONFIG_DOOR_LOCK_GESTURE_ACCESS_FRAME_FORWARDING=n
